services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${API_PORT}
    environment:
      NODE_ENV: development
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
  db:
    image: mysql
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_TCP_PORT=${DB_PORT}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  db_data: